name: Daily ESPN Fantasy Football Digest

on:
  schedule:
    # Run daily at 6:00 AM Central Time (12:00 PM UTC during CST, 11:00 AM UTC during CDT)
    # Note: GitHub Actions uses UTC time, so we need to account for daylight saving time
    # During CST (winter): 6am CT = 12pm UTC
    # During CDT (summer): 6am CT = 11am UTC
    # We'll use 12pm UTC as the primary schedule since fantasy football season is typically during CST
    - cron: '0 12 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create token file from base64
      run: |
        echo "${{ secrets.GMAIL_TOKEN_B64 }}" | base64 -d > token.json
        
    - name: Run ESPN Activity Digest
      env:
        LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        YEAR: ${{ secrets.YEAR }}
        SWID: ${{ secrets.SWID }}
        ESPN_S2: ${{ secrets.ESPN_S2 }}
        LOOKBACK_HOURS: ${{ secrets.LOOKBACK_HOURS || '24' }}
        DEBUG: '0'
        GMAIL_TOKEN_B64: ${{ secrets.GMAIL_TOKEN_B64 }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO || '' }}
        EMAIL_CC: ${{ secrets.EMAIL_CC || '' }}
        EMAIL_BCC: ${{ secrets.EMAIL_BCC || '' }}
      run: |
        python main.py
        
    - name: Clean up token file
      if: always()
      run: |
        rm -f token.json
